# Generated by Django 2.1.5 on 2019-03-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspost',
            name='sender',
        ),
        migrations.DeleteModel(
            name='NewsPost',
        ),
    ]
