# Generated by Django 2.1.5 on 2019-03-25 20:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_manager', '0001_initial'),
        ('mainApp', '0002_auto_20190325_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('text', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('actual_time', models.IntegerField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts_manager.Profile')),
            ],
        ),
    ]
