# Generated by Django 2.1.5 on 2019-03-25 20:55

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_newspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspost',
            name='actual_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Actual time for post (in days)'),
        ),
        migrations.AlterField(
            model_name='newspost',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
