# Generated by Django 2.1.5 on 2019-03-25 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20190325_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newspost',
            old_name='actual_time',
            new_name='limitation_time',
        ),
    ]
