# Generated by Django 2.1.5 on 2019-04-02 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_manager', '0001_initial'),
        ('mainApp', '0010_auto_20190402_0605'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='implementers',
            field=models.ManyToManyField(related_name='implementers', to='accounts_manager.Profile'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts_manager.Profile'),
        ),
    ]
